# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_acc_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def __init__(self, title, type_, currency_full, currency_short, description, balance, add_to_all_balance):
        self._title = title
        self._type = type_
        self._currency_full = currency_full
        self._currency_short = currency_short
        self._description = description
        self._balance = balance
        self._add_to_all_balance = add_to_all_balance

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 82)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(9, 9, 9, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setObjectName("title")
        self.horizontalLayout_2.addWidget(self.title)
        self.desription = QtWidgets.QLabel(self.frame)
        self.desription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.desription.setObjectName("desription")
        self.horizontalLayout_2.addWidget(self.desription)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.balance_currency = QtWidgets.QLabel(self.frame)
        self.balance_currency.setObjectName("balance_currency")
        self.horizontalLayout.addWidget(self.balance_currency)
        self.btn_more_info = QtWidgets.QToolButton(self.frame)
        self.btn_more_info.setObjectName("btn_more_info")
        self.horizontalLayout.addWidget(self.btn_more_info)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", self._title))
        self.desription.setText(_translate("Form", self._description))
        self.balance_currency.setText(_translate("Form", f'{self._balance} {self._currency_short}'))
        self.btn_more_info.setText(_translate("Form", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
