# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from acc_object import Ui_Form
from menu_edit_acc import Ui_menu_edit_account
from menu_settings import Ui_SettingsMenu
from operation_object import Ui_frame_operation


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """Метод для прорисовки основного окна"""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.layout_main_window = QtWidgets.QWidget(MainWindow)
        self.layout_main_window.setObjectName("layout_main_window")
        self.gridLayout = QtWidgets.QGridLayout(self.layout_main_window)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_main_menu = QtWidgets.QTabWidget(self.layout_main_window)
        self.tab_main_menu.setObjectName("tab_main_menu")
        self.tab_accounts = QtWidgets.QWidget()
        self.tab_accounts.setObjectName("tab_accounts")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_accounts)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.h_layout_top_panel = QtWidgets.QHBoxLayout()
        self.h_layout_top_panel.setObjectName("h_layout_top_panel")
        self.btn_settings = QtWidgets.QToolButton(self.tab_accounts)
        self.btn_settings.setObjectName("btn_settings")
        self.h_layout_top_panel.addWidget(self.btn_settings)
        self.all_accounts_balance = QtWidgets.QLabel(self.tab_accounts)
        self.all_accounts_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.all_accounts_balance.setObjectName("all_accounts_balance")
        self.h_layout_top_panel.addWidget(self.all_accounts_balance)
        self.btn_crt_new_acc = QtWidgets.QToolButton(self.tab_accounts)
        self.btn_crt_new_acc.setObjectName("btn_crt_new_acc")
        self.h_layout_top_panel.addWidget(self.btn_crt_new_acc)
        self.verticalLayout_3.addLayout(self.h_layout_top_panel)
        self.frame_panel_accs = QtWidgets.QFrame(self.tab_accounts)
        self.frame_panel_accs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_panel_accs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panel_accs.setObjectName("frame_panel_accs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_panel_accs)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name_panel_accs = QtWidgets.QLabel(self.frame_panel_accs)
        self.name_panel_accs.setObjectName("name_panel_accs")
        self.horizontalLayout_3.addWidget(self.name_panel_accs)
        self.all_accs_balance = QtWidgets.QLabel(self.frame_panel_accs)
        self.all_accs_balance.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_accs_balance.setObjectName("all_accs_balance")
        self.horizontalLayout_3.addWidget(self.all_accs_balance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_panel_accs)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 812, 191))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_16.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_13.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.frame_panel_accs)
        self.frame_panel_savings = QtWidgets.QFrame(self.tab_accounts)
        self.frame_panel_savings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_panel_savings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panel_savings.setObjectName("frame_panel_savings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_panel_savings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_savings = QtWidgets.QHBoxLayout()
        self.panel_savings.setObjectName("panel_savings")
        self.name_panel_savings = QtWidgets.QLabel(self.frame_panel_savings)
        self.name_panel_savings.setObjectName("name_panel_savings")
        self.panel_savings.addWidget(self.name_panel_savings)
        self.all_savings_balance = QtWidgets.QLabel(self.frame_panel_savings)
        self.all_savings_balance.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_savings_balance.setObjectName("all_savings_balance")
        self.panel_savings.addWidget(self.all_savings_balance)
        self.verticalLayout.addLayout(self.panel_savings)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_panel_savings)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 812, 190))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.verticalLayout_3.addWidget(self.frame_panel_savings)
        self.tab_main_menu.addTab(self.tab_accounts, "")
        self.tab_categories = QtWidgets.QWidget()
        self.tab_categories.setObjectName("tab_categories")
        self.tab_main_menu.addTab(self.tab_categories, "")
        self.tab_operations = QtWidgets.QWidget()
        self.tab_operations.setObjectName("tab_operations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_operations)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.h_layout_top_panel_2 = QtWidgets.QHBoxLayout()
        self.h_layout_top_panel_2.setObjectName("h_layout_top_panel_2")
        self.btn_settings_3 = QtWidgets.QToolButton(self.tab_operations)
        self.btn_settings_3.setObjectName("btn_settings_3")
        self.h_layout_top_panel_2.addWidget(self.btn_settings_3)
        self.all_accounts_balance_3 = QtWidgets.QLabel(self.tab_operations)
        self.all_accounts_balance_3.setAlignment(QtCore.Qt.AlignCenter)
        self.all_accounts_balance_3.setObjectName("all_accounts_balance_3")
        self.h_layout_top_panel_2.addWidget(self.all_accounts_balance_3)
        self.btn_search_operation = QtWidgets.QToolButton(self.tab_operations)
        self.btn_search_operation.setObjectName("btn_search_operation")
        self.h_layout_top_panel_2.addWidget(self.btn_search_operation)
        self.verticalLayout_4.addLayout(self.h_layout_top_panel_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_date = QtWidgets.QToolButton(self.tab_operations)
        self.btn_date.setObjectName("btn_date")
        self.horizontalLayout_2.addWidget(self.btn_date)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.scroll_area_operations = QtWidgets.QScrollArea(self.tab_operations)
        self.scroll_area_operations.setWidgetResizable(True)
        self.scroll_area_operations.setObjectName("scroll_area_operations")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 832, 415))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_operations = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_operations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_operations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_operations.setObjectName("frame_operations")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_operations)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5.addWidget(self.frame_operations)
        spacerItem4 = QtWidgets.QSpacerItem(20, 345, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.scroll_area_operations.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scroll_area_operations)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btn_add_operation = QtWidgets.QToolButton(self.tab_operations)
        self.btn_add_operation.setObjectName("btn_add_operation")
        self.horizontalLayout.addWidget(self.btn_add_operation)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tab_main_menu.addTab(self.tab_operations, "")
        self.tab_overview = QtWidgets.QWidget()
        self.tab_overview.setObjectName("tab_overview")
        self.tab_main_menu.addTab(self.tab_overview, "")
        self.gridLayout.addWidget(self.tab_main_menu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.layout_main_window)

        self.retranslateUi(MainWindow)
        self.tab_main_menu.setCurrentIndex(0)

        self.all_accs_buttons = []
        self.frames_accs = []

        self.add_accounts_to_gui()
        self.update_balances()
        self.add_functions_to_buttons()
        self.btn_settings.clicked.connect(self.open_settings_menu)
        self.btn_add_operation.clicked.connect(self.draw_new_operation)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open_settings_menu(self):
        global SettingsMenu
        SettingsMenu = QtWidgets.QMainWindow()
        ui = Ui_SettingsMenu()
        ui.setupUi(SettingsMenu)
        SettingsMenu.show()

    def add_new_account(self, acc_object):
        global ui
        print(acc_object)
        """Метод прорисовывает счета на главном окне
        и связывает кнопки счетов с необходимыми функциями"""
        if acc_object['type'] == 'Обычный':
            account_object = QtWidgets.QWidget()
            ui = Ui_Form(acc_object)
            ui.setupUi(account_object)
            self.verticalLayout_16.addWidget(account_object)

        elif acc_object['type'] == 'Накопительный':
            account_object = QtWidgets.QWidget()
            ui = Ui_Form(acc_object)
            ui.setupUi(account_object)
            self.verticalLayout_15.addWidget(account_object)

        self.all_accs_buttons.append({'btn_acc': ui.btn_more_info, 'title': acc_object['title']})
        self.frames_accs.append(ui.frame)
        self.link_buttons_to_frames()

    def add_accounts_to_gui(self, only_last=False):
        """Метод для прорисовки всех имеющихся счетов"""
        with open('app_data/all_accounts.json', 'r', encoding='utf-8') as file:
            accounts_data = json.load(file)['accounts']

        if only_last:
            accounts_data = (accounts_data[-1],)

        for account in accounts_data:
            if not account['hide']:
                self.add_new_account(account)

    def update_balances(self):
        """Метод для обновления балансов на главном окне"""
        all_balance = all_accounts_balance = all_savings_balance = 0

        with open('app_data/all_accounts.json', 'r', encoding='utf-8') as file:
            all_accounts = json.load(file)['accounts']

        for account in all_accounts:
            if account['type'] == 'Обычный':
                all_accounts_balance += account['balance']
            elif account['type'] == 'Накопительный':
                all_savings_balance += account['balance']

            if account['add_to_all_balance']:
                all_balance += account['balance']

        self.all_accs_balance.setText(f'{self.remove_extra_zeros(round(all_accounts_balance, 2))} ₽')
        self.all_savings_balance.setText(f'{self.remove_extra_zeros(round(all_savings_balance, 2))} ₽')
        self.all_accounts_balance.setText(f'{self.remove_extra_zeros(round(all_balance, 2))} ₽')

    def update_accounts_gui(self):
        for account_frame in self.frames_accs:
            account_frame.deleteLater()
        self.frames_accs = []
        self.all_accs_buttons = []
        self.add_accounts_to_gui()

    @staticmethod
    def remove_extra_zeros(number):
        return int(number) if int(number) - number == 0.0 else number

    def add_functions_to_buttons(self, only_last=False):

        with open('app_data/all_accounts.json', 'r', encoding='utf-8') as file:
            accounts = json.load(file)['accounts']

        if only_last:
            accounts = (accounts[-1],)

        for btn_data in self.all_accs_buttons:
            for acc in accounts:
                if btn_data['title'] == acc['title']:
                    btn_data.update({'acc_data': acc})

        for button in self.all_accs_buttons:
            button['btn_acc'].released.connect(
                lambda btn=button: self.show_edit_acc_menu(btn))

    def link_buttons_to_frames(self):
        for i in range(len(self.frames_accs)):
            self.all_accs_buttons[i]['frame'] = self.frames_accs[i]

    def show_edit_acc_menu(self, account_btn):
        global menu_edit_account
        menu_edit_account = QtWidgets.QDialog()
        ui = Ui_menu_edit_account(self)
        ui.setupUi(menu_edit_account)
        ui.fill_in_with_data(account_btn)
        menu_edit_account.show()

    def draw_new_operation(self):
        frame_operation = QtWidgets.QFrame(self.scroll_area_operations)
        ui = Ui_frame_operation()
        ui.setupUi(frame_operation)
        self.verticalLayout_7.addWidget(frame_operation)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MoneyTrack"))
        self.btn_settings.setText(_translate("MainWindow", "S"))
        self.all_accounts_balance.setText(_translate("MainWindow", "0"))
        self.btn_crt_new_acc.setText(_translate("MainWindow", "+"))
        self.name_panel_accs.setText(_translate("MainWindow", "СЧЕТА"))
        self.all_accs_balance.setText(_translate("MainWindow", "0"))
        self.name_panel_savings.setText(_translate("MainWindow", "СБЕРЕЖЕНИЯ"))
        self.all_savings_balance.setText(_translate("MainWindow", "0"))
        self.tab_main_menu.setTabText(self.tab_main_menu.indexOf(self.tab_accounts), _translate("MainWindow", "Счета"))
        self.tab_main_menu.setTabText(self.tab_main_menu.indexOf(self.tab_categories),
                                      _translate("MainWindow", "Категории"))
        self.btn_settings_3.setText(_translate("MainWindow", "S"))
        self.all_accounts_balance_3.setText(_translate("MainWindow", "0"))
        self.btn_search_operation.setText(_translate("MainWindow", "S"))
        self.btn_date.setText(_translate("MainWindow", "Date"))
        self.btn_add_operation.setText(_translate("MainWindow", "+"))
        self.tab_main_menu.setTabText(self.tab_main_menu.indexOf(self.tab_operations),
                                      _translate("MainWindow", "Операции"))
        self.tab_main_menu.setTabText(self.tab_main_menu.indexOf(self.tab_overview), _translate("MainWindow", "Обзор"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
