# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_operation_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frame_operation(object):
    def setupUi(self, frame_operation):
        frame_operation.setObjectName("frame_operation")
        frame_operation.resize(400, 63)
        self.horizontalLayout = QtWidgets.QHBoxLayout(frame_operation)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IMAGE = QtWidgets.QLabel(frame_operation)
        self.IMAGE.setObjectName("IMAGE")
        self.horizontalLayout.addWidget(self.IMAGE)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(frame_operation)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(frame_operation)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(frame_operation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(frame_operation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(frame_operation)
        QtCore.QMetaObject.connectSlotsByName(frame_operation)

    def retranslateUi(self, frame_operation):
        _translate = QtCore.QCoreApplication.translate
        frame_operation.setWindowTitle(_translate("frame_operation", "Frame"))
        self.IMAGE.setText(_translate("frame_operation", "IMAGE"))
        self.label.setText(_translate("frame_operation", "Category (Under category)"))
        self.label_2.setText(_translate("frame_operation", "Account"))
        self.label_3.setText(_translate("frame_operation", "amount"))
        self.label_4.setText(_translate("frame_operation", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frame_operation = QtWidgets.QFrame()
    ui = Ui_frame_operation()
    ui.setupUi(frame_operation)
    frame_operation.show()
    sys.exit(app.exec_())
